### PR TITLE
adjust license&notice

### PR DESCRIPTION
**Pull request by wangkirin**

### CODE REVIEW

**Comment by yangbor** [comment]
1. Third party NOTICE files should be included(prometheus)
2. There's no need to keep a separate copy of apache 2.0 license for third party libraries

**Comment by asim** [comment]
Can you actually remove licenses when your original works were based on them? What you are left with is modified code. You cannot strip references just because you now no longer fork the code.

**Comment by yangbor** [comment]
@asim What I mean is remove the duplicated Apache License 2.0 content. Of course the copyright&notice for all third parties(including go-micro) which will be included in the release must be kept in the LICENSE/NOTICE. So it will be something like this:

Apache License 2.0 content
...

For xxx/go-micro-originated-content.go
This product bundles content from go-micro which is under Apache License 2.0. ....

As for the part of vendor, they will not be covered by the LICENSE/NOTICE as per Apache policy.
http://www.apache.org/dev/licensing-howto.html

**Comment by zhanbei** [comment]
According to https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/ , I suppose by "adjust license&notice" you mean what this Pull Request does but not the purpose of this PR which is expected.

> Include the purpose of this Pull Request. For example:
> > This is a spike to explore…
> > This simplifies the display of…
> > This fixes handling of…

This comment is just a suggestion that I would like to point out and I hope it didn't bother you. Thanks.

**Comment by wangkirin** [comment]
Thanks for all the  reviews and suggestions, I will reconsider this PR

**Pull request closed without merging**
