### PR TITLE
Add Travis Configuration

### PR DESCRIPTION
**Pull request by asifdxtreme**
https://github.com/ServiceComb/go-chassis/issues/3
Preview : 
image

### CODE REVIEW

**Comment by wangkirin** [comment]
LGTM

**Comment by wangkirin** [comment]
Should we add Unit Test in Travis-CI ?  @asifdxtreme @tianxiaoliang

**Comment by tianxiaoliang** [comment]
Must add UT verification

**Comment by asifdxtreme** [comment]
@wangkirin @tianxiaoliang  we will go step by step,  this PR is for build and basic verification,  in sometime we will raise another PR for UT and other static checks

**Comment by wangkirin** [comment]
@asifdxtreme  OK,  I am fine with that

**Pull request merged**
