### PR TITLE
Adjust fasthttp to vendor

### PR DESCRIPTION
**Pull request by wangkirin**
This PR is about the following works:
1.  adjust  import fasthttp from third_party folder to vendor
2.  remove `third_party/valaya/fasthttp`  folder
3.  adjust `LICENSE` and `NOTICE`

### CODE REVIEW

**Comment by tianxiaoliang** [comment]
do those functions still work:
1. we add 1-2 convenience APIs
2. Host name capital is ignored in fasthttp, but we follow the net/http don't ignore capital

**Comment by wangkirin** [comment]
About the first point , from my study , we just add  `HeaderMap()`  to convert header to a map , it can be replaced by use origin  interface 
[`req.GetRequest().Header.VisitAll()`  ](https://github.com/valyala/fasthttp/blob/master/header.go#L761)

```go
req.GetRequest().Header.VisitAll(func(key, value []byte) {
			h[string(key)] = string(value)
	})
```

About the second point , could you provide more details ?

**Comment by tianxiaoliang** [comment]
if  url is http://Server/ net/http will still use Server as host, but fasthttp will convert it to server, service center permit user to use upper case

**Comment by wangkirin** [comment]
@tianxiaoliang I googled this issue , it seems that the `domain name` or `host` in url is case insensitive,  so I think may the all convert to lower case is fine , what do you think  @asifdxtreme

**Pull request closed without merging**
